# Generated by Django 5.1.2 on 2024-10-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('in_prog', 'In Progress'), ('on_pause', 'On Pause')], default='in_prog', max_length=10),
        ),
    ]
