# Generated by Django 5.1.2 on 2024-11-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_pic',
            field=models.ImageField(blank=True, null=True, upload_to='comment_pics/'),
        ),
    ]
